### ISSUE TITLE
有报错 

### ISSUE THREAD

**Issue by GanNingBJ** [ruoyu-chen/hadoop-docker#14]

**Comment by GanNingBJ** [comment]
执行第一步 docker-compose up -d  这个执行后 
[root@izbp16a8zevmp2fmomrbxlz hadoop-docker-centos7]# sudo docker-compose up -d
Traceback (most recent call last):
  File "/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.9.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 17, in <module>
    from . import errors
  File "/usr/lib/python2.7/site-packages/compose/cli/errors.py", line 10, in <module>
    from docker.errors import APIError
  File "/usr/lib/python2.7/site-packages/docker/__init__.py", line 6, in <module>
    from .client import Client, AutoVersionClient, from_env # flake8: noqa
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 5, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from .packages.urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 95, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'requests.packages.urllib3'

**Comment by ruoyu-chen** [comment]
看上去是你那边docker环境的问题，有更详细的日志吗？docker版本，操作系统版本是什么

**Comment by GanNingBJ** [comment]
1、后来查出来是requests 版本不是最新，更新到最新就行了，后来又有一步提示缺少一个文件夹，创建就行了，这是不是一个小坑，哈哈
2、这个是基于本机去做的一个集群，如何基于三台机器去做集群呢，还能用到此容器吗
