### ISSUE TITLE
格式化hdfs namenode的时候保存。是没有权限，请问有没有遇到这种情况。

### ISSUE THREAD

**Issue by linsongze** [ruoyu-chen/hadoop-docker#6]
java.io.IOException: Cannot create directory /works/dfs/name/current
	at org.apache.hadoop.hdfs.server.common.Storage$StorageDirectory.clearDirectory(Storage.java:337)
	at org.apache.hadoop.hdfs.server.namenode.NNStorage.format(NNStorage.java:548)
	at org.apache.hadoop.hdfs.server.namenode.NNStorage.format(NNStorage.java:569)
	at org.apache.hadoop.hdfs.server.namenode.FSImage.format(FSImage.java:161)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:991)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1429)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1554)
17/05/19 17:15:52 ERROR namenode.NameNode: Failed to start namenode.
java.io.IOException: Cannot create directory /works/dfs/name/current
	at org.apache.hadoop.hdfs.server.common.Storage$StorageDirectory.clearDirectory(Storage.java:337)
	at org.apache.hadoop.hdfs.server.namenode.NNStorage.format(NNStorage.java:548)
	at org.apache.hadoop.hdfs.server.namenode.NNStorage.format(NNStorage.java:569)
	at org.apache.hadoop.hdfs.server.namenode.FSImage.format(FSImage.java:161)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:991)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1429)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1554)
17/05/19 17:15:52 INFO util.ExitUtil: Exiting with status 1

**Comment by ruoyu-chen** [comment]
1.这个docker镜像使用了很多文件卷，所以使用的过程中必须用docker-compose来启动和挂载文件卷。
2.在第一次启动HDFS之前必须要先格式化namenode

**Comment by linsongze** [comment]
docker-compose exec spark-master hdfs namenode -format
目前遇到的问题，就是按照您的步骤，在格式化的时候。报这个异常了。

**Comment by ruoyu-chen** [comment]
你可以使用下面的命令进入docker容器的命令行：docker-compose exec spark-master bash 
然后你可以访问一下/works/这个目录看是否存在。
另外你查看一下你使用的docker-compose.yml文件，里面是否设置了文件卷。
如果还有问题，你需要把你使用的软件环境贴上来。

**Comment by linsongze** [comment]
先谢谢你。这边貌似解决了。是selinux的权限导致的，一个是禁用权限检查#setenforce 0。另外一个可以在compose文件中加入privileged: true。

**Comment by linsongze** [comment]
#docker-compose exec spark-master hadoop fs -mkdir /user/
#docker-compose exec spark-master hadoop fs -mkdir /user/spark/
#docker-compose exec spark-master hadoop fs -mkdir /user/spark/share/
#docker-compose exec spark-master hadoop fs -mkdir /user/spark/share/lib/

**Comment by ruoyu-chen** [comment]
这个目录我在本地的工程中处理了，忘记推送到github上来了，谢谢提醒
docker-compose exec spark-master hadoop fs -mkdir -p /user/spark/share/lib/
